DROP TABLE IF EXISTS people;

CREATE TABLE people (
  id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR2(255) NOT NULL DEFAULT '',
  last_name VARCHAR2(255) NOT NULL DEFAULT '',
  email VARCHAR2(255) NOT NULL DEFAULT '',
  phone VARCHAR2(20)
);
